# Generated by Django 4.2 on 2023-10-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('goods', 'Goods')], default='service', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemday',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemtracker',
            name='debt',
            field=models.BooleanField(default=False, help_text='Click the box if purchase is on credit', verbose_name='Credit/Debit'),
        ),
    ]
