# Generated by Django 4.2 on 2023-10-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_itemtracker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtracker',
            old_name='date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
